version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/php:7.0
    steps:
      - run: sudo git clone https://github.com/mmeyer2k/semlock /tmp/semlock
      - run: sudo docker-php-ext-install sysvsem
      - run: composer --no-interaction --no-scripts --no-ansi --prefer-dist -a install
      - run: php /tmp/semlock/test.php
