version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/php:7.0
    steps:
      - run: sudo docker-php-ext-install sysvsem
      - run: git clone https://github.com/mmeyer2k/semlock $CIRCLE_WORKING_DIRECTORY
      - run: composer --no-interaction --no-scripts --no-ansi --prefer-dist -a install
      - run: whoami ; pwd ; echo $CIRCLE_WORKING_DIRECTORY
      - run: cd $CIRCLE_WORKING_DIRECTORY ; php test.php
