version: 2
jobs:
  build:
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/php:7.0
    steps:
      - checkout
      - run: apt install -y php7.0-sysvsem
      - run: composer --no-interaction --no-scripts --no-ansi --prefer-dist -a install
